name: Package & Deploy Nuget Package

on:
  release:
    types: [published]

permissions:
  packages: write
  contents: read
  actions: read

jobs:
  deploy-package-github:
    uses: TheKingOfLettuce/LettuceGithubWorkflows/.github/workflows/Upload-Nuget-dotnet.yml@main
    with:
      dotnet-version: 8.0.x
      configuration: Release
      artifact-name: LettuceTalk.Core_${{ github.ref_name }}
      bin-dir: LettuceTalk.Core
      nuget-source: https://nuget.pkg.github.com/TheKingOfLettuce/index.json
    secrets:
      nuget-api-key: ${{ secrets.GITHUB_TOKEN }}
